---


- name: Download EPEL release for CentOS
  get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: "{{  download_home }}/"

- name: Install Python pip
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - python-pip
  - "{{  download_home }}/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  - collectd

- name: upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Download CloudWatch agent Signature file
  get_url:
    url: "{{ centos.cwa_signature_link }}"
    dest: "{{  download_home }}/"

- name: Download CloudWatch agent Installer package file
  get_url:
    url: "{{ centos.cwa_package_link }}"
    dest: "{{  download_home }}/"

- name: Verify downloaded package signature
  command: gpg --verify {{ centos.cwa_signature }} {{ centos.cwa_package }}
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ download_home }}"

- name: Install CloudWatch agent 
  yum:
    name: "{{  download_home }}/{{ centos.cwa_package }}"
    disable_gpg_check: true
    state: present
