---

- name: Create necessary folders
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ download_home }}"
    - "{{ install_home }}"

- name: Install for CentOS/RedHat
  include: amazon.yml
  when: ansible_distribution == 'Amazon'

- name: Install for CentOS/RedHat
  include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Install for CentOS/RedHat
  include: redhat.yml
  when: ansible_distribution == 'RHEL' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install for Debian/Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Configure and verify
  include: configure.yml
