---

- name: Make sure universe repository is enabled
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    update_cache: yes

- name: Install pip
  apt:
    name: [ "python-pip", "collectd" ]
    state: present

- name: Download CloudWatch agent Signature file
  get_url:
    url: "{{ ubuntu.cwa_signature_link }}"
    dest: "{{  download_home }}/"

- name: Download CloudWatch agent Installer package file
  get_url:
    url: "{{ ubuntu.cwa_package_link }}"
    dest: "{{  download_home }}/"

- name: Verify downloaded package signature
  command: gpg --verify {{ ubuntu.cwa_signature }} {{ ubuntu.cwa_package }}
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr or 'gpg: no valid OpenPGP data found' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ download_home }}"

- name: Install CloudWatch agent 
  apt:
    deb: "{{ download_home }}/{{ ubuntu.cwa_package }}"
    state: present
