---

- name: Prevent packages from being upgraded
  dpkg_selections:
    name: "*"
    selection: hold

- name: make sure packages are installed
  apt:
    pkg: python3-pip
    state: present

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Check if CloudWatch agent is already installed
  stat:
    path: "{{ install_home }}/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl"
  register: result

- name: Fail when CloudWatch agent is already installed
  fail: 
    msg: "CloudWatch agent is already installed"
  when: result.stat.exists is true

- name: Download Signature file
  get_url:
    url: "{{ ubuntu.cwa_signature_link }}"
    dest: "{{  download_home }}/"

- name: Download Installer package file
  get_url:
    url: "{{ ubuntu.cwa_package_link }}"
    dest: "{{  download_home }}/"

- name: Verify downloaded package signature
  command: gpg --verify {{ cwa_signature }} {{ cwa_package }}
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr or 'gpg: no valid OpenPGP data found' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ download_home }}"

- name: Install package
  apt:
    deb: "{{ download_home }}/{{ cwa_package }}"
    state: present

- name: Configure cloudwatch
  template:
    src: config.json.j2
    dest: "{{ install_home }}/amazon-cloudwatch-agent/etc/config.json"

- name: Check installation
  shell: {{ install_home }}/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a start
  register: result

- debug: 
    var: result

- name: Fail when installation is not successful
  fail: 
    msg: "CloudWatch agent installation failed"
  when: result.stat.islnk is not defined