---

- name: If /var/lib/dpkg/lock is not released, kill the process
  block:
  - wait_for:
      path: /var/lib/dpkg/lock
      state: absent
      timeout: 300
    ignore_error: yes
    register: is_lock_released
  - debug:
      msg: "/var/lib/dpkg/lock is not released even after 5 minutes. Process is killed"
    when: is_lock_released.failed
  - file: 
      path: /var/lib/dpkg/lock
      state: absent
    when: is_lock_released.failed

- name: Install pip
  apt:
    name: [ "python3-pip", "collectd" ]
    state: present

- name: Ensure boto3 and botocore modules are installed
  pip:
    name: ["boto3", "botocore"]
    extra_args: "--user"

- name: Download CloudWatch agent Signature file
  get_url:
    url: "{{ ubuntu.cwa_signature_link }}"
    dest: "{{  download_home }}/"

- name: Download CloudWatch agent Installer package file
  get_url:
    url: "{{ ubuntu.cwa_package_link }}"
    dest: "{{  download_home }}/"

- name: Verify downloaded package signature
  command: gpg --verify {{ ubuntu.cwa_signature }} {{ ubuntu.cwa_package }}
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr or 'gpg: no valid OpenPGP data found' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ download_home }}"

- name: Install CloudWatch agent 
  apt:
    deb: "{{ download_home }}/{{ ubuntu.cwa_package }}"
    state: present
