- name: Create Stage Folder
  win_file:
    path: C:\Temp
    state: directory
  
- name: Install python3
  win_chocolatey:
    name: "{{ item  }}"
    state: present
  with_items:
  - python3
  - awscli

- name: Install boto3
  win_command: pip3.exe install boto boto3 botocore

- name: install aws tools
  win_package:
    path: http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi
    state: present
    product_id: '{186A6440-3AD4-4E0E-ACC2-C098CA589290}'
    creates_path: 'C:\Program Files\Amazon\Ec2ConfigService'
